# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
imports:
  - { resource: 'timesheetMappings.yaml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
          $timesheetMappingParameter: '%timesheetMappings%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Application\:
      resource: '../src/Application/*'

    App\Domain\:
      resource: '../src/Domain/*'

    App\Infrastructure\:
      resource: '../src/Infrastructure/*'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Persistence\Vault\TimesheetVault:
      arguments:
        - '%env(TIMESHEET_DEVICE_CODE)%'

    App\Infrastructure\Persistence\Vault\TimeularVault:
      arguments:
        - '%env(TIMEULAR_API_KEY)%'
        - '%env(TIMEULAR_API_SECRET)%'
